version: '3.7'

services:
  sharebook:
    container_name: sharebook-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4200:4200'
